DEMO_SCENARIOS = [
    {
        "scenario_key": "ai-meeting-summary",
        "title": "Competitor launches AI meeting summarization",
        "description": "A competitor launched AI-powered meeting summaries with action items and CRM sync.",
        "event_type": "competitor_feature_launch",
        "market_event": {
            "title": "Competitor launches AI meeting summarization",
            "summary": "A competitor launched AI-powered meeting summaries with action items and CRM sync.",
            "why_it_matters": "Customers increasingly expect AI productivity features inside SaaS workflows.",
            "recommended_evolution": "Add an AI meeting insights module.",
            "importance_score": 0.86,
        },
        "research_evidence": [
            {
                "source": "controlled_demo",
                "title": "AI meeting features are becoming standard in productivity SaaS",
                "summary": "Meeting capture, action extraction, and CRM sync now appear in multiple productivity suites.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "Customer success teams value meeting-to-task automation",
                "summary": "Teams that run recurring customer calls benefit when follow-ups flow directly into task systems.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "Retention impact rises when core workflows get AI assistance",
                "summary": "AI assistance inside daily meeting workflows can increase perceived product stickiness.",
                "relevance": "medium",
                "url": None,
            },
        ],
        "expected_recommendation": "Add an AI meeting insights module.",
        "scores": {
            "business_impact": 0.87,
            "technical_complexity": 0.58,
            "urgency": 0.78,
            "confidence": 0.84,
            "risk_score": 0.32,
        },
        "tags": ["ai", "meetings", "competitor", "retention"],
        "proposed_files": [
            {"file_path": "docs/features/ai-meeting-insights.md", "artifact_type": "documentation"},
            {"file_path": "demo/generated/meeting-summary-widget.tsx", "artifact_type": "component"},
            {"file_path": "demo/generated/impact-analysis.json", "artifact_type": "report"},
        ],
    },
    {
        "scenario_key": "github-rag-trend",
        "title": "RAG repositories are trending on GitHub",
        "description": "Developer tools using retrieval-augmented generation are trending rapidly.",
        "event_type": "developer_trend",
        "market_event": {
            "title": "RAG repositories are trending on GitHub",
            "summary": "Developer tools using retrieval-augmented generation are trending rapidly.",
            "why_it_matters": "SaaS teams are adopting knowledge-aware AI assistants.",
            "recommended_evolution": "Add a knowledge base assistant foundation.",
            "importance_score": 0.79,
        },
        "research_evidence": [
            {
                "source": "controlled_demo",
                "title": "Knowledge-aware assistants are moving from prototype to product",
                "summary": "Teams increasingly expect AI assistants to cite internal docs and respect product context.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "RAG patterns fit AcmeFlow's knowledge base module",
                "summary": "Existing knowledge base content can become a retrieval layer before broader automation.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "Developer adoption can shape product-led AI expectations",
                "summary": "Open-source momentum makes technical buyers more comfortable with RAG-backed features.",
                "relevance": "medium",
                "url": None,
            },
        ],
        "expected_recommendation": "Add a knowledge base assistant foundation.",
        "scores": {
            "business_impact": 0.74,
            "technical_complexity": 0.68,
            "urgency": 0.72,
            "confidence": 0.80,
            "risk_score": 0.41,
        },
        "tags": ["rag", "github", "knowledge-base", "developer-tools"],
        "proposed_files": [
            {"file_path": "docs/features/knowledge-assistant.md", "artifact_type": "documentation"},
            {"file_path": "demo/generated/rag-architecture.md", "artifact_type": "plan"},
            {"file_path": "demo/generated/vector-memory-plan.json", "artifact_type": "config"},
        ],
    },
    {
        "scenario_key": "security-compliance-shift",
        "title": "Market shift toward AI security compliance",
        "description": "SaaS buyers are asking for stronger audit logs, AI traceability, and compliance-ready controls.",
        "event_type": "buyer_requirement_shift",
        "market_event": {
            "title": "Market shift toward AI security compliance",
            "summary": "SaaS buyers are asking for stronger audit logs, AI traceability, and compliance-ready controls.",
            "why_it_matters": "Enterprise customers need explainability and governance.",
            "recommended_evolution": "Add AI audit trail and compliance dashboard.",
            "importance_score": 0.88,
        },
        "research_evidence": [
            {
                "source": "controlled_demo",
                "title": "Enterprise AI evaluations now include traceability requirements",
                "summary": "Procurement teams increasingly ask how AI actions were decided, reviewed, and logged.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "Audit trails reduce perceived adoption risk",
                "summary": "Transparent AI records help operations teams trust automated recommendations.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "Compliance dashboards can support enterprise readiness",
                "summary": "Governance surfaces can turn security questions into a visible product strength.",
                "relevance": "high",
                "url": None,
            },
        ],
        "expected_recommendation": "Add AI audit trail and compliance dashboard.",
        "scores": {
            "business_impact": 0.89,
            "technical_complexity": 0.64,
            "urgency": 0.83,
            "confidence": 0.86,
            "risk_score": 0.36,
        },
        "tags": ["security", "compliance", "audit", "enterprise"],
        "proposed_files": [
            {"file_path": "docs/features/ai-audit-trail.md", "artifact_type": "documentation"},
            {"file_path": "demo/generated/audit-log-schema.json", "artifact_type": "schema"},
            {"file_path": "demo/generated/compliance-dashboard-plan.md", "artifact_type": "plan"},
        ],
    },
    {
        "scenario_key": "competitor-automation",
        "title": "Competitor releases autonomous workflow builder",
        "description": "A competitor released a no-code autonomous workflow builder with AI planning support.",
        "event_type": "competitor_feature_launch",
        "market_event": {
            "title": "Competitor releases autonomous workflow builder",
            "summary": "A competitor released a no-code autonomous workflow builder with AI planning support.",
            "why_it_matters": "Workflow automation is becoming a key differentiator.",
            "recommended_evolution": "Add autonomous workflow templates and recommendation engine.",
            "importance_score": 0.94,
        },
        "research_evidence": [
            {
                "source": "controlled_demo",
                "title": "No-code automation is becoming a buying criterion",
                "summary": "Operations teams prefer tools that turn repeated processes into reusable workflow templates.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "AI planning can reduce workflow setup friction",
                "summary": "Planning support makes automation approachable for non-technical product and ops teams.",
                "relevance": "high",
                "url": None,
            },
            {
                "source": "controlled_demo",
                "title": "Competitive urgency is highest when core differentiation shifts",
                "summary": "Autonomous workflow builders sit near AcmeFlow's tasks, projects, and integrations modules.",
                "relevance": "high",
                "url": None,
            },
        ],
        "expected_recommendation": "Add autonomous workflow templates and recommendation engine.",
        "scores": {
            "business_impact": 0.93,
            "technical_complexity": 0.72,
            "urgency": 0.91,
            "confidence": 0.88,
            "risk_score": 0.44,
        },
        "tags": ["automation", "competitor", "workflow-builder", "roadmap"],
        "proposed_files": [
            {"file_path": "docs/features/autonomous-workflow-templates.md", "artifact_type": "documentation"},
            {"file_path": "demo/generated/workflow-template-schema.json", "artifact_type": "schema"},
            {"file_path": "demo/generated/recommendation-engine-plan.md", "artifact_type": "plan"},
        ],
    },
]
