from __future__ import annotations

from typing import Any

import httpx

from app.core.config import settings


class GitHubPRClientError(RuntimeError):
    pass


class GitHubBranchExistsError(GitHubPRClientError):
    pass


class GitHubPRClient:
    """Small GitHub REST client for draft PR creation through the Git data API."""

    def __init__(self, token: str | None = None) -> None:
        self.token = token if token is not None else settings.GITHUB_TOKEN
        self.base_url = settings.GITHUB_API_BASE_URL.rstrip("/")

    def create_draft_pr(
        self,
        *,
        owner: str,
        repo: str,
        base_branch: str,
        branch_name: str,
        title: str,
        body: str,
        files: list[dict[str, str]],
        draft: bool = True,
    ) -> dict[str, Any]:
        base_ref = self.safe_request("GET", f"/repos/{owner}/{repo}/git/ref/heads/{base_branch}")
        base_sha = self._nested(base_ref, "object", "sha")
        if not base_sha:
            raise GitHubPRClientError("base_branch_missing")

        base_commit = self.safe_request("GET", f"/repos/{owner}/{repo}/git/commits/{base_sha}")
        base_tree_sha = self._nested(base_commit, "tree", "sha")
        if not base_tree_sha:
            raise GitHubPRClientError("base_tree_missing")

        self.safe_request(
            "POST",
            f"/repos/{owner}/{repo}/git/refs",
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
        )

        tree_entries = []
        for file in files:
            blob = self.safe_request(
                "POST",
                f"/repos/{owner}/{repo}/git/blobs",
                json={"content": file["content"], "encoding": "utf-8"},
            )
            blob_sha = blob.get("sha") if isinstance(blob, dict) else None
            if not blob_sha:
                raise GitHubPRClientError("blob_create_failed")
            tree_entries.append({"path": file["path"], "mode": "100644", "type": "blob", "sha": blob_sha})

        tree = self.safe_request(
            "POST",
            f"/repos/{owner}/{repo}/git/trees",
            json={"base_tree": base_tree_sha, "tree": tree_entries},
        )
        tree_sha = tree.get("sha") if isinstance(tree, dict) else None
        if not tree_sha:
            raise GitHubPRClientError("tree_create_failed")

        commit = self.safe_request(
            "POST",
            f"/repos/{owner}/{repo}/git/commits",
            json={
                "message": f"{title}\n\nGenerated by EvolvAI in safe draft PR mode.",
                "tree": tree_sha,
                "parents": [base_sha],
                "author": {
                    "name": settings.GITHUB_PR_COMMIT_AUTHOR_NAME,
                    "email": settings.GITHUB_PR_COMMIT_AUTHOR_EMAIL,
                },
            },
        )
        commit_sha = commit.get("sha") if isinstance(commit, dict) else None
        if not commit_sha:
            raise GitHubPRClientError("commit_create_failed")

        self.safe_request(
            "PATCH",
            f"/repos/{owner}/{repo}/git/refs/heads/{branch_name}",
            json={"sha": commit_sha, "force": False},
        )

        pr = self.safe_request(
            "POST",
            f"/repos/{owner}/{repo}/pulls",
            json={
                "title": title,
                "body": body,
                "head": branch_name,
                "base": base_branch,
                "draft": draft,
            },
        )
        return {
            "number": pr.get("number"),
            "url": pr.get("html_url"),
            "branch_name": branch_name,
            "commit_sha": commit_sha,
        }

    def safe_request(
        self,
        method: str,
        path: str,
        json: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        if not self.token:
            raise GitHubPRClientError("missing_github_token")
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {self.token}",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "EvolvAI-Step6-Draft-PR",
        }
        url = f"{self.base_url}{path}"
        last_error: Exception | None = None
        for attempt in range(settings.GITHUB_MAX_RETRIES + 1):
            try:
                with httpx.Client(timeout=settings.GITHUB_REQUEST_TIMEOUT_SECONDS, headers=headers) as client:
                    response = client.request(method, url, json=json)
                if response.status_code == 422 and method == "POST" and path.endswith("/git/refs"):
                    raise GitHubBranchExistsError("branch_already_exists")
                if response.status_code == 401:
                    raise GitHubPRClientError("github_authentication_error")
                if response.status_code == 403:
                    message = self._response_message(response)
                    if response.headers.get("X-RateLimit-Remaining") == "0" or "rate limit" in message.lower():
                        raise GitHubPRClientError("github_rate_limit")
                    raise GitHubPRClientError("github_permission_error")
                if response.status_code == 404:
                    raise GitHubPRClientError("github_resource_missing")
                if response.status_code == 422:
                    raise GitHubPRClientError(f"github_validation_error: {self._response_message(response)}")
                if response.status_code in {500, 502, 503, 504} and attempt < settings.GITHUB_MAX_RETRIES:
                    last_error = GitHubPRClientError(f"github_server_error_{response.status_code}")
                    continue
                response.raise_for_status()
                try:
                    return response.json()
                except ValueError as exc:
                    raise GitHubPRClientError("github_malformed_json") from exc
            except (GitHubBranchExistsError, GitHubPRClientError):
                raise
            except httpx.TimeoutException as exc:
                last_error = exc
                if attempt >= settings.GITHUB_MAX_RETRIES:
                    raise GitHubPRClientError("github_timeout") from exc
            except httpx.HTTPError as exc:
                last_error = exc
                if attempt >= settings.GITHUB_MAX_RETRIES:
                    raise GitHubPRClientError("github_network_error") from exc
        raise GitHubPRClientError(str(last_error or "github_request_failed"))

    def _response_message(self, response: httpx.Response) -> str:
        try:
            payload = response.json()
        except ValueError:
            return response.text[:200]
        if isinstance(payload, dict):
            return str(payload.get("message") or "github_error")
        return "github_error"

    def _nested(self, payload: dict[str, Any], *keys: str) -> Any:
        current: Any = payload
        for key in keys:
            if not isinstance(current, dict):
                return None
            current = current.get(key)
        return current
