SYSTEM_CONNECTED = "system.connected"
WORKFLOW_JOIN = "workflow.join"

WORKFLOW_CREATED = "workflow.created"
WORKFLOW_QUEUED = "workflow.queued"
WORKFLOW_STARTED = "workflow.started"
WORKFLOW_UPDATED = "workflow.updated"
WORKFLOW_COMPLETED = "workflow.completed"
WORKFLOW_FAILED = "workflow.failed"
WORKFLOW_CANCELLED = "workflow.cancelled"

AGENT_STARTED = "agent.started"
AGENT_UPDATED = "agent.updated"
AGENT_COMPLETED = "agent.completed"
AGENT_FAILED = "agent.failed"

LOG_CREATED = "log.created"
MARKET_EVENT_CREATED = "market_event.created"
DECISION_CREATED = "decision.created"
PR_CREATED = "pr.created"
PR_OPENED = "pr.opened"
PR_FAILED = "pr.failed"
NOTIFICATION_CREATED = "notification.created"

SCENARIO_SELECTED = "scenario.selected"
MARKET_EVENT_NORMALIZED = "market_event.normalized"
RESEARCH_COMPLETED = "research.completed"
IMPACT_CREATED = "impact.created"
EXPLAINABILITY_CREATED = "explainability.created"
ARTIFACT_GENERATED = "artifact.generated"
VERIFICATION_COMPLETED = "verification.completed"
PR_PREVIEW_CREATED = "pr.preview.created"
DEMO_COMPLETED = "demo.completed"

LLM_STARTED = "llm.started"
LLM_COMPLETED = "llm.completed"
LLM_FAILED = "llm.failed"
LLM_FALLBACK_USED = "llm.fallback_used"

LIVE_EVENT_INGESTION_STARTED = "live_event.ingestion_started"
LIVE_EVENT_INGESTION_COMPLETED = "live_event.ingestion_completed"
LIVE_EVENT_INGESTION_FAILED = "live_event.ingestion_failed"
LIVE_EVENT_CREATED = "live_event.created"
LIVE_EVENT_DEDUPED = "live_event.deduped"
LIVE_EVENT_WORKFLOW_TRIGGERED = "live_event.workflow_triggered"

AGENT_LLM_ENHANCED = "agent.llm_enhanced"
AGENT_DETERMINISTIC_FALLBACK = "agent.deterministic_fallback"
